exporters:
    cloudwatch: {}
receivers:
    disk: {}
    mem: {}
service:
    metrics:
        exporters:
            - disk
            - mem
        processors: []
        receivers:
            - cloudwatch
