exporters:
    cloudwatch: {}
receivers:
    diskio: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors: []
            receivers:
                - diskio
