exporters:
    cloudwatchlogs: {}
receivers:
    prometheus_scraper: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatchlogs
            processors: []
            receivers:
                - prometheus_scraper
